import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'category', label: 'Overview', items: ['intro'] },
    {
      type: 'category',
      label: 'Services',
      items: [
        {
          type: 'category',
          label: 'Identity Fabric',
          link: { type: 'doc', id: 'services/identity-fabric/index' },
          items: [],
        },
        {
          type: 'category',
          label: 'CRUD Service',
          link: { type: 'doc', id: 'services/crud-service/index' },
          items: [
            {
              type: 'category',
              label: 'How‑to',
              items: [
                'services/crud-service/how-to/migration-guide-visual-designer',
                'services/crud-service/how-to/bff-startup-dcr-iat',
                'services/crud-service/how-to/enable-mtls',
              ],
            },
            {
              type: 'category',
              label: 'Secrets Platform',
              link: { type: 'doc', id: 'services/crud-service/secrets/index' },
              items: [
                { type: 'autogenerated', dirName: 'services/crud-service/secrets' },
              ],
            },
            {
              type: 'category',
              label: 'Explanations',
              items: [{ type: 'autogenerated', dirName: 'services/crud-service/explanation' }],
            },
            {
              type: 'category',
              label: 'Reference',
              link: { type: 'generated-index', title: 'CRUD Service Reference', description: 'Reference docs for CRUD Service. This page is generated and will list all reference topics as they are added.' },
              items: [{ type: 'autogenerated', dirName: 'services/crud-service/reference' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'BFF',
          link: { type: 'doc', id: 'services/bff/index' },
          items: [
            {
              type: 'category',
              label: 'Tutorials',
              items: [{ type: 'autogenerated', dirName: 'services/bff/tutorials' }],
            },
            {
              type: 'category',
              label: 'How‑to',
              items: [{ type: 'autogenerated', dirName: 'services/bff/how-to' }],
            },
            {
              type: 'category',
              label: 'Explanations',
              items: [{ type: 'autogenerated', dirName: 'services/bff/explanation' }],
            },
            {
              type: 'category',
              label: 'Reference',
              items: [{ type: 'autogenerated', dirName: 'services/bff/reference' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'Experience',
          link: { type: 'doc', id: 'services/experience/index' },
          items: [
            { type: 'autogenerated', dirName: 'services/experience' }
          ],
        },
        {
          type: 'category',
          label: 'NowConnect',
          link: { type: 'doc', id: 'services/nowconnect/index' },
          items: [
            {
              type: 'category',
              label: 'How‑to',
              items: [{ type: 'autogenerated', dirName: 'services/nowconnect/how-to' }],
            },
            {
              type: 'category',
              label: 'Explanations',
              items: [{ type: 'autogenerated', dirName: 'services/nowconnect/explanation' }],
            },
            {
              type: 'category',
              label: 'Reference',
              items: [{ type: 'autogenerated', dirName: 'services/nowconnect/reference' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'IdP',
          link: { type: 'doc', id: 'services/idp/index' },
          items: [
            {
              type: 'category',
              label: 'How‑to',
              items: [{ type: 'autogenerated', dirName: 'services/idp/how-to' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'Experience',
          link: { type: 'doc', id: 'services/experience/index' },
          items: [
            'services/experience/experience_plugins',
            'services/experience/quickstart',
            'services/experience/plugin-starter',
            'services/experience/error-loading-patterns',
            'services/experience/performance-budgets',
            'services/experience/developer-types',
            'services/experience/local-dev-mock',
            'services/experience/plugins-storage-deployment',
            'services/experience/plugin_guide',
            'services/experience/ops-runbook',
            'services/experience/security-compliance',
            'services/experience/security-reference',
            'services/experience/api-reference',
            'services/experience/cicd-cookbook',
            'services/experience/monitoring-alerts',
            'services/experience/versioning-compatibility',
            'services/experience/authorization-authzen',
            'services/experience/qa-test-plan',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Personas',
      items: [
        'personas/faq',
        'personas/sales',
        'personas/admins',
        'personas/security/intro',
        'personas/devops',
        'personas/frontend',
        'personas/backend',
        'personas/auditors',
        'personas/testers',
      ],
    },
    {
      type: 'category',
      label: 'Marketing',
      items: [
        'marketing/index',
        'marketing/positioning',
        'marketing/identity-fabric-standards',
        'marketing/experience-app',
        'marketing/go-to-market',
        'marketing/packaging-pricing',
        'marketing/personas',
        'marketing/competitive',
        'marketing/studio-backend-mapping',
        'marketing/naming-service',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
